language: java
jdk:
  - oraclejdk8
script: env && ./mvnw package -B
before_deploy: ./ci/travis_beforeDeploy.sh
deploy:
   edge: true
   provider: cloudfoundry
   username: tkess17@gmail.com
   password: 
   api: https://api.run.pivotal.io
   organization: tkess17-org
   space: development
